
services:
  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "3000:80"   # Web UI
      - "2525:25"   # SMTP
      # - "143:143" # IMAP (optional)

  mandrill-dev:
    build: .
    container_name: mandrill-dev
    depends_on:
      - smtp4dev
    environment:
      - PORT=8080
      - DEBUG=true
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_TLS=none
      # - MANDRILL_KEYS=dev1,dev2   # optional
    ports:
      - "8080:8080"

