
services:
  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "3000:80"   # Web UI
      - "2525:25"   # SMTP
      # - "143:143" # IMAP (optional)

  mandrill-dev:
    build: .
    container_name: mandrill-dev
    depends_on:
      - smtp4dev
    environment:
      - PORT=8080
      - DEBUG=true
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_TLS=none
      # - MANDRILL_KEYS=dev1,dev2   # optional
    ports:
      - "8080:8080"

  client:
    image: golang:1.25.1
    depends_on:
      mandrill-dev:
        condition: service_healthy
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      - API_BASE=http://mandrill-dev:8080
      - KEY=dev
      - FROM=sender@example.com
      - TO=user@example.com
      - REPLY_TO=reply@example.com
    command: ["go","run","./examples/go-client"]

  bun-http-client:
    image: oven/bun:1.2
    depends_on:
      mandrill-dev:
        condition: service_healthy
    working_dir: /src/examples/node-client
    volumes:
      - ./:/src
    environment:
      - API_BASE=http://mandrill-dev:8080
      - KEY=dev
      - FROM=sender@example.com
      - TO=user@example.com
      - REPLY_TO=reply@example.com
    command: ["bun","http-client.js"]


  bun-sdk-client:
    image: oven/bun:1.2
    depends_on:
      mandrill-dev:
        condition: service_healthy
    working_dir: /src/examples/node-client
    volumes:
      - ./:/src
    environment:
      - MC_BASE=http://mandrill-dev:8080/api/1.0
      - KEY=dev
      - FROM=sender@example.com
      - TO=user@example.com
      - REPLY_TO=reply@example.com
    command: ["bun","sdk-client.js"]

  bun-send-template-client:
    image: oven/bun:1.2
    depends_on:
      mandrill-dev:
        condition: service_healthy
    working_dir: /src/examples/node-client
    volumes:
      - ./:/src
    environment:
      - MC_BASE=http://mandrill-dev:8080/api/1.0
      - KEY=dev
      - FROM=sender@example.com
      - TO=user@example.com
      - REPLY_TO=reply@example.com
    command: ["bun","send-template.js"]
